name: ${project.name}
main: skinsrestorer.bukkit.SkinsRestorer
version: ${project.version}
description: ${project.description}
website: https://github.com/dev-braini/SkinEvent
authors: [braini]
softdepend: [Multiverse-Core, MultiWorld]
commands:
  skinsrestorer:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Main command.
permissions:
   skinsrestorer.playercmds:
     description: Allows access to all main commands.
     default: op
   skinsrestorer.playercmds.menu:
     description: Allows access to the /skins command.
   skinsrestorer.cmds:
     description: Allows access to administrative commands.
     default: op
   skinsrestorer.bypasscooldown:
     description: Bypasses any set cooldowns in the config.
     default: op
   skinsrestorer.bypassdisabled:
     description: Allows access to disabled skins in the config.
     default: op
