name: ${project.name}
main: skinevent.bukkit.SkinEvent
version: ${project.version}
description: ${project.description}
website: https://github.com/dev-braini/SkinEvent
authors: [braini]
softdepend: [Multiverse-Core, MultiWorld]
commands:
  skinevent:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Main command.
permissions:
   skinevent.playercmds:
     description: Allows access to all main commands.
     default: op
   skinevent.playercmds.menu:
     description: Allows access to the /skins command.
   skinevent.cmds:
     description: Allows access to administrative commands.
     default: op
   skinevent.bypasscooldown:
     description: Bypasses any set cooldowns in the config.
     default: op
   skinevent.bypassdisabled:
     description: Allows access to disabled skins in the config.
     default: op
