name: ${project.name}
main: skinevent.bukkit.SkinEvent
version: ${project.version}
description: ${project.description}
website: https://github.com/dev-braini/SkinEvent
authors: [braini]
softdepend: [Multiverse-Core, MultiWorld]
commands:
  skin:
    description: Main command.
  skinevent:
    aliases: [sr]
    permission: skinevent.skinupdate
    description: Admin commands.
permissions:
   skinevent.skinupdate:
     description: Allows access to all main commands.
     default: true
   skinevent.startevent:
     description: Allows access to the /skin event command.
   skinevent.admin:
     description: Allows access to administrative commands.
     default: op